[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.pdo_pgsql", "nodejs_20", "git"]

[phases.build]
dependsOn = ["setup"]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build"
]

[start]
cmd = "php artisan config:clear && php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT"
